package com.example.aoc24

import com.example.solutions.DaySolution8
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Test

class DaySolution8Test {
    private val solution = DaySolution8(TestLogger())

    @Test
    fun testPart1() = runTest {
        input8.forEachIndexed { id, str -> solution.part1.handleLine(str, id) }
        solution.part1.finish()
        assertEquals(result, solution.part1.obtainResult())
    }

    @Test
    fun testPart2() = runTest {
        input8.forEachIndexed { id, str -> solution.part2.handleLine(str, id) }
        solution.part2.finish()
        assertEquals(result, solution.part2.obtainResult())
    }

    private val input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".trimMargin().split("\n")

    private val input2 = """......
......
...a..
......
..a...
......
......
    """.trimMargin().split("\n")
    private val input3 = """..........
..........
..........
....a.....
........a.
.....a....
..........
......A...
..........
..........""".trimMargin().split("\n")


    private val result = "14"

}